--- @class nvl.config.mod_info
--- @field [1] string The module name to import from
--- @field [2]? string The symbol inside the module
---
--- @class nvl.package.ConfigOptionsExports
--- @field globals table<string,nvl.config.mod_info>
---
--- @class nvl.package.ConfigOptionsBase
--- @field exports table

--- @class nvl.package.config_exports
--- @field setup fun(options:nvl.package.ConfigOptionsBase):boolean setup function of a package
---
