--- @class nvl.package.ConfigOptionsExports
--- @field globals table<string,nvl.config.mod_info>
---
--- @class nvl.package.ConfigOptionsBase
--- @field exports table

--- @class nvl.package.config_exports
--- @field setup fun(options:nvl.package.ConfigOptionsBase):boolean setup function of a package
---
--- @alias nvl.OperatingSystem "linux"|"mac"|"windows"|"wsl"|"wsl2"|"bsd"
---
