name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        rev: [nightly, v0.9.5, v0.10.0]
        lua-version: ["5.4"]
        luarocks-version: ["3.11.1"]

  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v1.0.2
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: "The library provides commonly used functions and classes for Lua and Neovim runtimes."
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Install Lua
        uses: leafo/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}
      - name: Unit test
        run: |
          mkdir .tmp
          make test
          make coverage
